import functionals
import numpy as np
import random
import math

def task_1():
    cube1 = functionals.Box.from_diagonal(np.array([0, 0, 0]), np.array([1, 1, 1]))
    pR_1 = functionals.make_rotation_around_vector(cube1.p1, np.array([1, 1, 0]), 45)
    pR_2 = functionals.make_rotation_around_vector(cube1.p2, np.array([1, 1, 0]), 45)
    pR_3 = functionals.make_rotation_around_vector(cube1.p3, np.array([1, 1, 0]), 45)
    pR_4 = functionals.make_rotation_around_vector(cube1.p4, np.array([1, 1, 0]), 45)
    pR_5 = functionals.make_rotation_around_vector(cube1.p5, np.array([1, 1, 0]), 45)
    pR_6 = functionals.make_rotation_around_vector(cube1.p6, np.array([1, 1, 0]), 45)
    pR_7 = functionals.make_rotation_around_vector(cube1.p7, np.array([1, 1, 0]), 45)
    pR_8 = functionals.make_rotation_around_vector(cube1.p8, np.array([1, 1, 0]), 45)
    cube2 = functionals.Box.from_points(pR_1, pR_2, pR_3, pR_4, pR_5, pR_6, pR_7, pR_8)
    print("Перша трансформація:")
    cube2.printer()
    print(functionals.get_R_matrix_for_rotate_around_vector(np.array([1, 1, 0]), 45))
    pT_1 = functionals.make_translation(cube2.p1, 2, -1, 3)
    pT_2 = functionals.make_translation(cube2.p2, 2, -1, 3)
    pT_3 = functionals.make_translation(cube2.p3, 2, -1, 3)
    pT_4 = functionals.make_translation(cube2.p4, 2, -1, 3)
    pT_5 = functionals.make_translation(cube2.p5, 2, -1, 3)
    pT_6 = functionals.make_translation(cube2.p6, 2, -1, 3)
    pT_7 = functionals.make_translation(cube2.p7, 2, -1, 3)
    pT_8 = functionals.make_translation(cube2.p8, 2, -1, 3)
    cube3 = functionals.Box.from_points(pT_1, pT_2, pT_3, pT_4, pT_5, pT_6, pT_7, pT_8)
    print("Друга трансформація:")
    cube3.printer()
    print(functionals.get_translate_matrix(2, -1, 3))

def task_2():
    cube1 = functionals.Box.from_diagonal(np.array([0, 0, 0]), np.array([1, 1, 1]))
    pS_1 = functionals.make_scale(cube1.p1, 2, 0.5, 1)
    pS_2 = functionals.make_scale(cube1.p2, 2, 0.5, 1)
    pS_3 = functionals.make_scale(cube1.p3, 2, 0.5, 1)
    pS_4 = functionals.make_scale(cube1.p4, 2, 0.5, 1)
    pS_5 = functionals.make_scale(cube1.p5, 2, 0.5, 1)
    pS_6 = functionals.make_scale(cube1.p6, 2, 0.5, 1)
    pS_7 = functionals.make_scale(cube1.p7, 2, 0.5, 1)
    pS_8 = functionals.make_scale(cube1.p8, 2, 0.5, 1)
    cube2 = functionals.Box.from_points(pS_1, pS_2, pS_3, pS_4, pS_5, pS_6, pS_7, pS_8)
    print("Перша трансформація:")
    cube2.printer()
    print(functionals.get_scale_matrix(2, -0.5, 1))
    pR_1 = functionals.make_rotation_euler_xyz(cube2.p1, 30, 45, 60)
    pR_2 = functionals.make_rotation_euler_xyz(cube2.p2, 30, 45, 60)
    pR_3 = functionals.make_rotation_euler_xyz(cube2.p3, 30, 45, 60)
    pR_4 = functionals.make_rotation_euler_xyz(cube2.p4, 30, 45, 60)
    pR_5 = functionals.make_rotation_euler_xyz(cube2.p5, 30, 45, 60)
    pR_6 = functionals.make_rotation_euler_xyz(cube2.p6, 30, 45, 60)
    pR_7 = functionals.make_rotation_euler_xyz(cube2.p7, 30, 45, 60)
    pR_8 = functionals.make_rotation_euler_xyz(cube2.p8, 30, 45, 60)
    cube3 = functionals.Box.from_points(pR_1, pR_2, pR_3, pR_4, pR_5, pR_6, pR_7, pR_8)
    print("Друга трансформація:")
    cube3.printer()
    print(functionals.get_R_euler_matrix_xyz(30, 45, 60))
    pT_1 = functionals.make_translation(cube3.p1, -3, 2, 5)
    pT_2 = functionals.make_translation(cube3.p2, -3, 2, 5)
    pT_3 = functionals.make_translation(cube3.p3, -3, 2, 5)
    pT_4 = functionals.make_translation(cube3.p4, -3, 2, 5)
    pT_5 = functionals.make_translation(cube3.p5, -3, 2, 5)
    pT_6 = functionals.make_translation(cube3.p6, -3, 2, 5)
    pT_7 = functionals.make_translation(cube3.p7, -3, 2, 5)
    pT_8 = functionals.make_translation(cube3.p8, -3, 2, 5)
    cube4 = functionals.Box.from_points(pT_1, pT_2, pT_3, pT_4, pT_5, pT_6, pT_7, pT_8)
    print("Третя трансформація:")
    cube4.printer()
    print(functionals.get_translate_matrix(-3, 2, 5))

def task_3():
    cube1 = functionals.Box.from_diagonal(np.array([0, 0, 0]), np.array([1, 1, 1]))
    pR_1 = functionals.make_rotation_around_vector(cube1.p1, np.array([0, 0, 1]), 60)
    pR_2 = functionals.make_rotation_around_vector(cube1.p2, np.array([0, 0, 1]), 60)
    pR_3 = functionals.make_rotation_around_vector(cube1.p3, np.array([0, 0, 1]), 60)
    pR_4 = functionals.make_rotation_around_vector(cube1.p4, np.array([0, 0, 1]), 60)
    pR_5 = functionals.make_rotation_around_vector(cube1.p5, np.array([0, 0, 1]), 60)
    pR_6 = functionals.make_rotation_around_vector(cube1.p6, np.array([0, 0, 1]), 60)
    pR_7 = functionals.make_rotation_around_vector(cube1.p7, np.array([0, 0, 1]), 60)
    pR_8 = functionals.make_rotation_around_vector(cube1.p8, np.array([0, 0, 1]), 60)
    cube2 = functionals.Box.from_points(pR_1, pR_2, pR_3, pR_4, pR_5, pR_6, pR_7, pR_8)
    print("Перша трансформація:")
    cube2.printer()
    print(functionals.get_R_matrix_for_rotate_around_vector(np.array([0, 0, 1]), 60))
    pRR_1 = functionals.make_rotation_around_vector(cube2.p1, np.array([1, 1, 1]), 45)
    pRR_2 = functionals.make_rotation_around_vector(cube2.p2, np.array([1, 1, 1]), 45)
    pRR_3 = functionals.make_rotation_around_vector(cube2.p3, np.array([1, 1, 1]), 45)
    pRR_4 = functionals.make_rotation_around_vector(cube2.p4, np.array([1, 1, 1]), 45)
    pRR_5 = functionals.make_rotation_around_vector(cube2.p5, np.array([1, 1, 1]), 45)
    pRR_6 = functionals.make_rotation_around_vector(cube2.p6, np.array([1, 1, 1]), 45)
    pRR_7 = functionals.make_rotation_around_vector(cube2.p7, np.array([1, 1, 1]), 45)
    pRR_8 = functionals.make_rotation_around_vector(cube2.p8, np.array([1, 1, 1]), 45)
    cube3 = functionals.Box.from_points(pRR_1, pRR_2, pRR_3, pRR_4, pRR_5, pRR_6, pRR_7, pRR_8)
    print("Друга трансформація:")
    cube3.printer()
    print(functionals.get_R_matrix_for_rotate_around_vector(np.array([1, 1, 1]), 45))
    pT_1 = functionals.make_translation(cube3.p1, 4, -2, 1)
    pT_2 = functionals.make_translation(cube3.p2, 4, -2, 1)
    pT_3 = functionals.make_translation(cube3.p3, 4, -2, 1)
    pT_4 = functionals.make_translation(cube3.p4, 4, -2, 1)
    pT_5 = functionals.make_translation(cube3.p5, 4, -2, 1)
    pT_6 = functionals.make_translation(cube3.p6, 4, -2, 1)
    pT_7 = functionals.make_translation(cube3.p7, 4, -2, 1)
    pT_8 = functionals.make_translation(cube3.p8, 4, -2, 1)
    cube4 = functionals.Box.from_points(pT_1, pT_2, pT_3, pT_4, pT_5, pT_6, pT_7, pT_8)
    print("Третя трансформація:")
    cube4.printer()
    print(functionals.get_translate_matrix(4, -2, 1))

def task_4():
    cube1 = functionals.Box.from_diagonal(np.array([0, 0, 0]), np.array([1, 1, 1]))
    pR_1 = functionals.make_rotation_euler_zyx(cube1.p1, 20, 35, 50)
    pR_2 = functionals.make_rotation_euler_zyx(cube1.p2, 20, 35, 50)
    pR_3 = functionals.make_rotation_euler_zyx(cube1.p3, 20, 35, 50)
    pR_4 = functionals.make_rotation_euler_zyx(cube1.p4, 20, 35, 50)
    pR_5 = functionals.make_rotation_euler_zyx(cube1.p5, 20, 35, 50)
    pR_6 = functionals.make_rotation_euler_zyx(cube1.p6, 20, 35, 50)
    pR_7 = functionals.make_rotation_euler_zyx(cube1.p7, 20, 35, 50)
    pR_8 = functionals.make_rotation_euler_zyx(cube1.p8, 20, 35, 50)
    cube2 = functionals.Box.from_points(pR_1, pR_2, pR_3, pR_4, pR_5, pR_6, pR_7, pR_8)
    print("Перша трансформація:")
    cube2.printer()
    print(functionals.get_R_euler_matrix_zyx(20, 35, 50))
    pT_1 = functionals.make_translation(cube2.p1, 1, 3, -2)
    pT_2 = functionals.make_translation(cube2.p2, 1, 3, -2)
    pT_3 = functionals.make_translation(cube2.p3, 1, 3, -2)
    pT_4 = functionals.make_translation(cube2.p4, 1, 3, -2)
    pT_5 = functionals.make_translation(cube2.p5, 1, 3, -2)
    pT_6 = functionals.make_translation(cube2.p6, 1, 3, -2)
    pT_7 = functionals.make_translation(cube2.p7, 1, 3, -2)
    pT_8 = functionals.make_translation(cube2.p8, 1, 3, -2)
    cube3 = functionals.Box.from_points(pT_1, pT_2, pT_3, pT_4, pT_5, pT_6, pT_7, pT_8)
    print("Друга трансформація:")
    cube3.printer()
    print(functionals.get_translate_matrix(1, 3, -2))

def task_5():
    angle = random.uniform(10, 90)
    axis_x = random.uniform(-5, 5)
    axis_y = random.uniform(-5, 5)
    axis_z = random.uniform(-5, 5)
    while axis_x == 0 and axis_y == 0 and axis_z == 0:
        axis_x = random.uniform(-5, 5)
        axis_y = random.uniform(-5, 5)
        axis_z = random.uniform(-5, 5)
    t_x = random.uniform(-5, 5)
    t_y = random.uniform(-5, 5)
    t_z = random.uniform(-5, 5)
    axis = np.array([axis_x, axis_y, axis_z])

    tetra1 = functionals.Tetrahedron.default()

    print("Згенерований кут:")
    print(angle)
    print("Згенерована вісь:")
    print(axis)
    print("Згенерований вектор переміщення:")
    print(np.array([t_x, t_y, t_z]))

    pR_1 = functionals.make_rotation_around_vector(tetra1.p1, axis, angle)
    pR_2 = functionals.make_rotation_around_vector(tetra1.p2, axis, angle)
    pR_3 = functionals.make_rotation_around_vector(tetra1.p3, axis, angle)
    pR_4 = functionals.make_rotation_around_vector(tetra1.p4, axis, angle)
    tetra2 = functionals.Tetrahedron.from_points(pR_1, pR_2, pR_3, pR_4)
    print("Перша трансформація:")
    tetra2.printer()
    print(functionals.get_R_matrix_for_rotate_around_vector(axis, angle))

    pT_1 = functionals.make_translation(tetra2.p1, t_x, t_y, t_z)
    pT_2 = functionals.make_translation(tetra2.p2, t_x, t_y, t_z)
    pT_3 = functionals.make_translation(tetra2.p3, t_x, t_y, t_z)
    pT_4 = functionals.make_translation(tetra2.p4, t_x, t_y, t_z)
    tetra3 = functionals.Tetrahedron.from_points(pT_1, pT_2, pT_3, pT_4)
    print("Друга трансформація:")
    tetra3.printer()
    print(functionals.get_translate_matrix(t_x, t_y, t_z))

def task_6():
    cube1 = functionals.Box.from_diagonal(np.array([0, 0, 0]), np.array([1, 1, 1]))
    pT_1 = functionals.make_translation(cube1.p1, -2, 0, -3)
    pT_2 = functionals.make_translation(cube1.p2, -2, 0, -3)
    pT_3 = functionals.make_translation(cube1.p3, -2, 0, -3)
    pT_4 = functionals.make_translation(cube1.p4, -2, 0, -3)
    pT_5 = functionals.make_translation(cube1.p5, -2, 0, -3)
    pT_6 = functionals.make_translation(cube1.p6, -2, 0, -3)
    pT_7 = functionals.make_translation(cube1.p7, -2, 0, -3)
    pT_8 = functionals.make_translation(cube1.p8, -2, 0, -3)
    pR_1 = functionals.make_rotation_around_vector(pT_1, np.array([0, 1, 0]), 45)
    pR_2 = functionals.make_rotation_around_vector(pT_2, np.array([0, 1, 0]), 45)
    pR_3 = functionals.make_rotation_around_vector(pT_3, np.array([0, 1, 0]), 45)
    pR_4 = functionals.make_rotation_around_vector(pT_4, np.array([0, 1, 0]), 45)
    pR_5 = functionals.make_rotation_around_vector(pT_5, np.array([0, 1, 0]), 45)
    pR_6 = functionals.make_rotation_around_vector(pT_6, np.array([0, 1, 0]), 45)
    pR_7 = functionals.make_rotation_around_vector(pT_7, np.array([0, 1, 0]), 45)
    pR_8 = functionals.make_rotation_around_vector(pT_8, np.array([0, 1, 0]), 45)
    pTT_1 = functionals.make_translation(pR_1, 2, 0, 3)
    pTT_2 = functionals.make_translation(pR_2, 2, 0, 3)
    pTT_3 = functionals.make_translation(pR_3, 2, 0, 3)
    pTT_4 = functionals.make_translation(pR_4, 2, 0, 3)
    pTT_5 = functionals.make_translation(pR_5, 2, 0, 3)
    pTT_6 = functionals.make_translation(pR_6, 2, 0, 3)
    pTT_7 = functionals.make_translation(pR_7, 2, 0, 3)
    pTT_8 = functionals.make_translation(pR_8, 2, 0, 3)
    cube2 = functionals.Box.from_points(pTT_1, pTT_2, pTT_3, pTT_4, pTT_5, pTT_6, pTT_7, pTT_8)
    print("Перша трансформація:")
    cube2.printer()
    print(functionals.get_translate_matrix(2, 0, 3) @ functionals.get_R_matrix_for_rotate_around_vector(np.array([0, 1, 0]), 45) @ functionals.get_translate_matrix(-2, 0, -3))
    pT2_1 = functionals.make_translation(cube2.p1, -1, 2, 4)
    pT2_2 = functionals.make_translation(cube2.p2, -1, 2, 4)
    pT2_3 = functionals.make_translation(cube2.p3, -1, 2, 4)
    pT2_4 = functionals.make_translation(cube2.p4, -1, 2, 4)
    pT2_5 = functionals.make_translation(cube2.p5, -1, 2, 4)
    pT2_6 = functionals.make_translation(cube2.p6, -1, 2, 4)
    pT2_7 = functionals.make_translation(cube2.p7, -1, 2, 4)
    pT2_8 = functionals.make_translation(cube2.p8, -1, 2, 4)
    cube3 = functionals.Box.from_points(pT2_1, pT2_2, pT2_3, pT2_4, pT2_5, pT2_6, pT2_7, pT2_8)
    print("Друга трансформація:")
    cube3.printer()
    print(functionals.get_translate_matrix(-1, 2, 4))


def task_7():
    cube1 = functionals.Box.from_diagonal(np.array([0, 0, 0]), np.array([1, 1, 1]))
    pT_1 = functionals.make_translation(cube1.p1, -1, -2, -3)
    pT_2 = functionals.make_translation(cube1.p2, -1, -2, -3)
    pT_3 = functionals.make_translation(cube1.p3, -1, -2, -3)
    pT_4 = functionals.make_translation(cube1.p4, -1, -2, -3)
    pT_5 = functionals.make_translation(cube1.p5, -1, -2, -3)
    pT_6 = functionals.make_translation(cube1.p6, -1, -2, -3)
    pT_7 = functionals.make_translation(cube1.p7, -1, -2, -3)
    pT_8 = functionals.make_translation(cube1.p8, -1, -2, -3)
    pS_1 = functionals.make_scale(pT_1, 1, 1, 3)
    pS_2 = functionals.make_scale(pT_2, 1, 1, 3)
    pS_3 = functionals.make_scale(pT_3, 1, 1, 3)
    pS_4 = functionals.make_scale(pT_4, 1, 1, 3)
    pS_5 = functionals.make_scale(pT_5, 1, 1, 3)
    pS_6 = functionals.make_scale(pT_6, 1, 1, 3)
    pS_7 = functionals.make_scale(pT_7, 1, 1, 3)
    pS_8 = functionals.make_scale(pT_8, 1, 1, 3)
    pTT_1 = functionals.make_translation(pS_1, 1, 2, 3)
    pTT_2 = functionals.make_translation(pS_2, 1, 2, 3)
    pTT_3 = functionals.make_translation(pS_3, 1, 2, 3)
    pTT_4 = functionals.make_translation(pS_4, 1, 2, 3)
    pTT_5 = functionals.make_translation(pS_5, 1, 2, 3)
    pTT_6 = functionals.make_translation(pS_6, 1, 2, 3)
    pTT_7 = functionals.make_translation(pS_7, 1, 2, 3)
    pTT_8 = functionals.make_translation(pS_8, 1, 2, 3)
    cube2 = functionals.Box.from_points(pTT_1, pTT_2, pTT_3, pTT_4, pTT_5, pTT_6, pTT_7, pTT_8)
    print("Перша трансформація:")
    cube2.printer()
    print(functionals.get_translate_matrix(1, 2, 3) @ functionals.get_scale_matrix(1, 1, 3) @ functionals.get_translate_matrix(-1, -2, -3))
    pT2_1 = functionals.make_translation(cube2.p1, -1, -2, -3)
    pT2_2 = functionals.make_translation(cube2.p2, -1, -2, -3)
    pT2_3 = functionals.make_translation(cube2.p3, -1, -2, -3)
    pT2_4 = functionals.make_translation(cube2.p4, -1, -2, -3)
    pT2_5 = functionals.make_translation(cube2.p5, -1, -2, -3)
    pT2_6 = functionals.make_translation(cube2.p6, -1, -2, -3)
    pT2_7 = functionals.make_translation(cube2.p7, -1, -2, -3)
    pT2_8 = functionals.make_translation(cube2.p8, -1, -2, -3)
    pR2_1 = functionals.make_rotation_around_vector(pT2_1, np.array([0, 0, 1]), 30)
    pR2_2 = functionals.make_rotation_around_vector(pT2_2, np.array([0, 0, 1]), 30)
    pR2_3 = functionals.make_rotation_around_vector(pT2_3, np.array([0, 0, 1]), 30)
    pR2_4 = functionals.make_rotation_around_vector(pT2_4, np.array([0, 0, 1]), 30)
    pR2_5 = functionals.make_rotation_around_vector(pT2_5, np.array([0, 0, 1]), 30)
    pR2_6 = functionals.make_rotation_around_vector(pT2_6, np.array([0, 0, 1]), 30)
    pR2_7 = functionals.make_rotation_around_vector(pT2_7, np.array([0, 0, 1]), 30)
    pR2_8 = functionals.make_rotation_around_vector(pT2_8, np.array([0, 0, 1]), 30)
    pTT2_1 = functionals.make_translation(pR2_1, 1, 2, 3)
    pTT2_2 = functionals.make_translation(pR2_2, 1, 2, 3)
    pTT2_3 = functionals.make_translation(pR2_3, 1, 2, 3)
    pTT2_4 = functionals.make_translation(pR2_4, 1, 2, 3)
    pTT2_5 = functionals.make_translation(pR2_5, 1, 2, 3)
    pTT2_6 = functionals.make_translation(pR2_6, 1, 2, 3)
    pTT2_7 = functionals.make_translation(pR2_7, 1, 2, 3)
    pTT2_8 = functionals.make_translation(pR2_8, 1, 2, 3)
    cube3 = functionals.Box.from_points(pTT2_1, pTT2_2, pTT2_3, pTT2_4, pTT2_5, pTT2_6, pTT2_7, pTT2_8)
    print("Друга трансформація:")
    cube3.printer()
    print(functionals.get_translate_matrix(1, 2, 3) @ functionals.get_R_matrix_for_rotate_around_vector(np.array([0, 0, 1]), 30) @ functionals.get_translate_matrix(-1, -2, -3))


def task_8():
    triangle1 = functionals.Triangle3D.default()
    pT_1 = functionals.make_translation(triangle1.p1, -2, -3, -4)
    pT_2 = functionals.make_translation(triangle1.p2, -2, -3, -4)
    pT_3 = functionals.make_translation(triangle1.p3, -2, -3, -4)
    pR_1 = functionals.make_rotation_around_vector(pT_1, np.array([1, 1, 1]), 90)
    pR_2 = functionals.make_rotation_around_vector(pT_2, np.array([1, 1, 1]), 90)
    pR_3 = functionals.make_rotation_around_vector(pT_3, np.array([1, 1, 1]), 90)
    pTT_1 = functionals.make_translation(pR_1, 2, 3, 4)
    pTT_2 = functionals.make_translation(pR_2, 2, 3, 4)
    pTT_3 = functionals.make_translation(pR_3, 2, 3, 4)
    triangle2 = functionals.Triangle3D.from_points(pTT_1, pTT_2, pTT_3)
    print("Перша трансформація:")
    triangle2.printer()
    print(functionals.get_translate_matrix(2, 3, 4) @ functionals.get_R_matrix_for_rotate_around_vector(np.array([1, 1, 1]), 90) @ functionals.get_translate_matrix(-2, -3, -4))
    pT2_1 = functionals.make_translation(triangle2.p1, 0, -3, 2)
    pT2_2 = functionals.make_translation(triangle2.p2, 0, -3, 2)
    pT2_3 = functionals.make_translation(triangle2.p3, 0, -3, 2)
    triangle3 = functionals.Triangle3D.from_points(pT2_1, pT2_2, pT2_3)
    print("Друга трансформація:")
    triangle3.printer()
    print(functionals.get_translate_matrix(0, -3, 2))


def task_9():
    rectangle1 = functionals.Rectangle3D.from_points(np.array([1, 2, 0, 1]), np.array([4, 2, 0, 1]), np.array([4, 5, 0, 1]), np.array([1, 5, 0, 1]))
    pT_1 = functionals.make_translation(rectangle1.p1, -3, -3, 0)
    pT_2 = functionals.make_translation(rectangle1.p2, -3, -3, 0)
    pT_3 = functionals.make_translation(rectangle1.p3, -3, -3, 0)
    pT_4 = functionals.make_translation(rectangle1.p4, -3, -3, 0)
    pR_1 = functionals.make_rotation_around_vector(pT_1, np.array([0, 1, 0]), 60)
    pR_2 = functionals.make_rotation_around_vector(pT_2, np.array([0, 1, 0]), 60)
    pR_3 = functionals.make_rotation_around_vector(pT_3, np.array([0, 1, 0]), 60)
    pR_4 = functionals.make_rotation_around_vector(pT_4, np.array([0, 1, 0]), 60)
    pTT_1 = functionals.make_translation(pR_1, 3, 3, 0)
    pTT_2 = functionals.make_translation(pR_2, 3, 3, 0)
    pTT_3 = functionals.make_translation(pR_3, 3, 3, 0)
    pTT_4 = functionals.make_translation(pR_4, 3, 3, 0)
    rectangle2 = functionals.Rectangle3D.from_points(pTT_1, pTT_2, pTT_3, pTT_4)
    print("Перша трансформація:")
    rectangle2.printer()
    print(functionals.get_translate_matrix(3, 3, 0) @ functionals.get_R_matrix_for_rotate_around_vector(np.array([0, 1, 0]), 60) @ functionals.get_translate_matrix(-3, -3, 0))
    pT2_1 = functionals.make_translation(rectangle2.p1, -3, -3, 0)
    pT2_2 = functionals.make_translation(rectangle2.p2, -3, -3, 0)
    pT2_3 = functionals.make_translation(rectangle2.p3, -3, -3, 0)
    pT2_4 = functionals.make_translation(rectangle2.p4, -3, -3, 0)
    pR2_1 = functionals.make_rotation_around_vector(pT2_1, np.array([1, 0, 0]), 30)
    pR2_2 = functionals.make_rotation_around_vector(pT2_2, np.array([1, 0, 0]), 30)
    pR2_3 = functionals.make_rotation_around_vector(pT2_3, np.array([1, 0, 0]), 30)
    pR2_4 = functionals.make_rotation_around_vector(pT2_4, np.array([1, 0, 0]), 30)
    pTT2_1 = functionals.make_translation(pR2_1, 3, 3, 0)
    pTT2_2 = functionals.make_translation(pR2_2, 3, 3, 0)
    pTT2_3 = functionals.make_translation(pR2_3, 3, 3, 0)
    pTT2_4 = functionals.make_translation(pR2_4, 3, 3, 0)
    rectangle3 = functionals.Rectangle3D.from_points(pTT2_1, pTT2_2, pTT2_3, pTT2_4)
    print("Друга трансформація:")
    rectangle3.printer()
    print(functionals.get_translate_matrix(3, 3, 0) @ functionals.get_R_matrix_for_rotate_around_vector(np.array([1, 0, 0]), 30) @ functionals.get_translate_matrix(-3, -3, 0))


def task_10():
    cube1 = functionals.Box.from_diagonal(np.array([0, 0, 0]), np.array([1, 1, 1]))
    pT_1 = functionals.make_translation(cube1.p1, -1, -1, -1)
    pT_2 = functionals.make_translation(cube1.p2, -1, -1, -1)
    pT_3 = functionals.make_translation(cube1.p3, -1, -1, -1)
    pT_4 = functionals.make_translation(cube1.p4, -1, -1, -1)
    pT_5 = functionals.make_translation(cube1.p5, -1, -1, -1)
    pT_6 = functionals.make_translation(cube1.p6, -1, -1, -1)
    pT_7 = functionals.make_translation(cube1.p7, -1, -1, -1)
    pT_8 = functionals.make_translation(cube1.p8, -1, -1, -1)
    pS_1 = functionals.make_scale(pT_1, 2, 1, 1)
    pS_2 = functionals.make_scale(pT_2, 2, 1, 1)
    pS_3 = functionals.make_scale(pT_3, 2, 1, 1)
    pS_4 = functionals.make_scale(pT_4, 2, 1, 1)
    pS_5 = functionals.make_scale(pT_5, 2, 1, 1)
    pS_6 = functionals.make_scale(pT_6, 2, 1, 1)
    pS_7 = functionals.make_scale(pT_7, 2, 1, 1)
    pS_8 = functionals.make_scale(pT_8, 2, 1, 1)
    pTT_1 = functionals.make_translation(pS_1, 1, 1, 1)
    pTT_2 = functionals.make_translation(pS_2, 1, 1, 1)
    pTT_3 = functionals.make_translation(pS_3, 1, 1, 1)
    pTT_4 = functionals.make_translation(pS_4, 1, 1, 1)
    pTT_5 = functionals.make_translation(pS_5, 1, 1, 1)
    pTT_6 = functionals.make_translation(pS_6, 1, 1, 1)
    pTT_7 = functionals.make_translation(pS_7, 1, 1, 1)
    pTT_8 = functionals.make_translation(pS_8, 1, 1, 1)
    cube2 = functionals.Box.from_points(pTT_1, pTT_2, pTT_3, pTT_4, pTT_5, pTT_6, pTT_7, pTT_8)
    print("Перша трансформація:")
    cube2.printer()
    print(functionals.get_translate_matrix(1, 1, 1) @ functionals.get_scale_matrix(2, 1, 1) @ functionals.get_translate_matrix(-1, -1, -1))
    pT2_1 = functionals.make_translation(cube2.p1, -1, -1, -1)
    pT2_2 = functionals.make_translation(cube2.p2, -1, -1, -1)
    pT2_3 = functionals.make_translation(cube2.p3, -1, -1, -1)
    pT2_4 = functionals.make_translation(cube2.p4, -1, -1, -1)
    pT2_5 = functionals.make_translation(cube2.p5, -1, -1, -1)
    pT2_6 = functionals.make_translation(cube2.p6, -1, -1, -1)
    pT2_7 = functionals.make_translation(cube2.p7, -1, -1, -1)
    pT2_8 = functionals.make_translation(cube2.p8, -1, -1, -1)
    pR2_1 = functionals.make_rotation_around_vector(pT2_1, np.array([0, 1, 0]), 45)
    pR2_2 = functionals.make_rotation_around_vector(pT2_2, np.array([0, 1, 0]), 45)
    pR2_3 = functionals.make_rotation_around_vector(pT2_3, np.array([0, 1, 0]), 45)
    pR2_4 = functionals.make_rotation_around_vector(pT2_4, np.array([0, 1, 0]), 45)
    pR2_5 = functionals.make_rotation_around_vector(pT2_5, np.array([0, 1, 0]), 45)
    pR2_6 = functionals.make_rotation_around_vector(pT2_6, np.array([0, 1, 0]), 45)
    pR2_7 = functionals.make_rotation_around_vector(pT2_7, np.array([0, 1, 0]), 45)
    pR2_8 = functionals.make_rotation_around_vector(pT2_8, np.array([0, 1, 0]), 45)
    pTT2_1 = functionals.make_translation(pR2_1, 1, 1, 1)
    pTT2_2 = functionals.make_translation(pR2_2, 1, 1, 1)
    pTT2_3 = functionals.make_translation(pR2_3, 1, 1, 1)
    pTT2_4 = functionals.make_translation(pR2_4, 1, 1, 1)
    pTT2_5 = functionals.make_translation(pR2_5, 1, 1, 1)
    pTT2_6 = functionals.make_translation(pR2_6, 1, 1, 1)
    pTT2_7 = functionals.make_translation(pR2_7, 1, 1, 1)
    pTT2_8 = functionals.make_translation(pR2_8, 1, 1, 1)
    cube3 = functionals.Box.from_points(pTT2_1, pTT2_2, pTT2_3, pTT2_4, pTT2_5, pTT2_6, pTT2_7, pTT2_8)
    print("Друга трансформація:")
    cube3.printer()
    print(functionals.get_translate_matrix(1, 1, 1) @ functionals.get_R_matrix_for_rotate_around_vector(np.array([0, 1, 0]), 45) @ functionals.get_translate_matrix(-1, -1, -1))
    pT3_1 = functionals.make_translation(cube3.p1, -3, 4, 2)
    pT3_2 = functionals.make_translation(cube3.p2, -3, 4, 2)
    pT3_3 = functionals.make_translation(cube3.p3, -3, 4, 2)
    pT3_4 = functionals.make_translation(cube3.p4, -3, 4, 2)
    pT3_5 = functionals.make_translation(cube3.p5, -3, 4, 2)
    pT3_6 = functionals.make_translation(cube3.p6, -3, 4, 2)
    pT3_7 = functionals.make_translation(cube3.p7, -3, 4, 2)
    pT3_8 = functionals.make_translation(cube3.p8, -3, 4, 2)
    cube4 = functionals.Box.from_points(pT3_1, pT3_2, pT3_3, pT3_4, pT3_5, pT3_6, pT3_7, pT3_8)
    print("Третя трансформація:")
    cube4.printer()
    print(functionals.get_translate_matrix(-3, 4, 2))

def task_11():
    cube1 = functionals.Box.from_diagonal(np.array([0, 0, 0]), np.array([1, 1, 1]))
    pA_1 = functionals.make_rotation_euler_xyz(cube1.p1, 30, 45, 60)
    pA_2 = functionals.make_rotation_euler_xyz(cube1.p2, 30, 45, 60)
    pA_3 = functionals.make_rotation_euler_xyz(cube1.p3, 30, 45, 60)
    pA_4 = functionals.make_rotation_euler_xyz(cube1.p4, 30, 45, 60)
    pA_5 = functionals.make_rotation_euler_xyz(cube1.p5, 30, 45, 60)
    pA_6 = functionals.make_rotation_euler_xyz(cube1.p6, 30, 45, 60)
    pA_7 = functionals.make_rotation_euler_xyz(cube1.p7, 30, 45, 60)
    pA_8 = functionals.make_rotation_euler_xyz(cube1.p8, 30, 45, 60)
    cube2 = functionals.Box.from_points(pA_1, pA_2, pA_3, pA_4, pA_5, pA_6, pA_7, pA_8)
    R_A = functionals.get_R_euler_matrix_xyz(30, 45, 60)
    print("Трансформація А:")
    cube2.printer()
    print(R_A)
    R_B = functionals.get_R_z_matrix(math.radians(60)) @ functionals.get_R_y_matrix(math.radians(45)) @ functionals.get_R_x_matrix(math.radians(30))
    pB_1 = R_B @ cube1.p1
    pB_2 = R_B @ cube1.p2
    pB_3 = R_B @ cube1.p3
    pB_4 = R_B @ cube1.p4
    pB_5 = R_B @ cube1.p5
    pB_6 = R_B @ cube1.p6
    pB_7 = R_B @ cube1.p7
    pB_8 = R_B @ cube1.p8
    cube3 = functionals.Box.from_points(pB_1, pB_2, pB_3, pB_4, pB_5, pB_6, pB_7, pB_8)
    print("Трансформація Б:")
    cube3.printer()
    print(R_B)
    print("Матриці співпадають:")
    print(np.allclose(R_A, R_B))

def task_12(M):
    A = M[:3, :3]
    t = M[:3, 3]
    s_x = np.linalg.norm(A[:, 0])
    s_y = np.linalg.norm(A[:, 1])
    s_z = np.linalg.norm(A[:, 2])
    scales = np.array([s_x, s_y, s_z])
    R = np.array([
        [A[0, 0] / s_x, A[0, 1] / s_y, A[0, 2] / s_z],
        [A[1, 0] / s_x, A[1, 1] / s_y, A[1, 2] / s_z],
        [A[2, 0] / s_x, A[2, 1] / s_y, A[2, 2] / s_z]
    ])
    ortho_check = R.T @ R
    is_orthogonal = np.allclose(ortho_check, np.eye(3), atol=1e-6)
    trace_R = np.trace(R)
    cos_phi = (trace_R - 1) / 2
    cos_phi = max(-1.0, min(1.0, cos_phi))
    phi = math.acos(cos_phi)
    if abs(phi) < 1e-8:
        axis = np.array([0.0, 0.0, 1.0])
    else:
        axis = np.array([
            R[2, 1] - R[1, 2],
            R[0, 2] - R[2, 0],
            R[1, 0] - R[0, 1]
        ]) / (2 * math.sin(phi))
        axis = axis / np.linalg.norm(axis)
    print("Вектор перенесення:")
    print(t)
    print("Масштабні коефіцієнти:")
    print(scales)
    print("Чиста матриця обертання:")
    print(R)
    print("Перевірка ортогональності:")
    print(ortho_check)
    print("Матриця ортогональна:")
    print(is_orthogonal)
    print("Одиничний вектор осі:")
    print(axis)
    print("Кут повороту в радіанах:")
    print(phi)
    print("Кут повороту в градусах:")
    print(math.degrees(phi))
    return t, scales, R, axis, math.degrees(phi)

def task_13():
    tetra1 = functionals.Tetrahedron.default()
    M_1 = functionals.get_R_x_matrix(math.radians(45))
    pR_1 = M_1 @ tetra1.p1
    pR_2 = M_1 @ tetra1.p2
    pR_3 = M_1 @ tetra1.p3
    pR_4 = M_1 @ tetra1.p4
    tetra2 = functionals.Tetrahedron.from_points(pR_1, pR_2, pR_3, pR_4)
    print("Перша трансформація:")
    tetra2.printer()
    print(M_1)
    M_2 = M_1 @ functionals.get_translate_matrix(0, 2, 0)
    pT_1 = M_2 @ tetra1.p1
    pT_2 = M_2 @ tetra1.p2
    pT_3 = M_2 @ tetra1.p3
    pT_4 = M_2 @ tetra1.p4
    tetra3 = functionals.Tetrahedron.from_points(pT_1, pT_2, pT_3, pT_4)
    print("Друга трансформація:")
    tetra3.printer()
    print(M_2)
    M_3 = M_2 @ functionals.get_R_z_matrix(math.radians(30))
    pRR_1 = M_3 @ tetra1.p1
    pRR_2 = M_3 @ tetra1.p2
    pRR_3 = M_3 @ tetra1.p3
    pRR_4 = M_3 @ tetra1.p4
    tetra4 = functionals.Tetrahedron.from_points(pRR_1, pRR_2, pRR_3, pRR_4)
    print("Третя трансформація:")
    tetra4.printer()
    print(M_3)

def task_15():
    cube1 = functionals.Box.from_diagonal(np.array([0, 0, 0]), np.array([1, 1, 1]))
    pT_1 = functionals.make_translation(cube1.p1, -1, -1, -1)
    pT_2 = functionals.make_translation(cube1.p2, -1, -1, -1)
    pT_3 = functionals.make_translation(cube1.p3, -1, -1, -1)
    pT_4 = functionals.make_translation(cube1.p4, -1, -1, -1)
    pT_5 = functionals.make_translation(cube1.p5, -1, -1, -1)
    pT_6 = functionals.make_translation(cube1.p6, -1, -1, -1)
    pT_7 = functionals.make_translation(cube1.p7, -1, -1, -1)
    pT_8 = functionals.make_translation(cube1.p8, -1, -1, -1)
    pS_1 = functionals.make_scale(pT_1, 2, 2, 2)
    pS_2 = functionals.make_scale(pT_2, 2, 2, 2)
    pS_3 = functionals.make_scale(pT_3, 2, 2, 2)
    pS_4 = functionals.make_scale(pT_4, 2, 2, 2)
    pS_5 = functionals.make_scale(pT_5, 2, 2, 2)
    pS_6 = functionals.make_scale(pT_6, 2, 2, 2)
    pS_7 = functionals.make_scale(pT_7, 2, 2, 2)
    pS_8 = functionals.make_scale(pT_8, 2, 2, 2)
    pTT_1 = functionals.make_translation(pS_1, 1, 1, 1)
    pTT_2 = functionals.make_translation(pS_2, 1, 1, 1)
    pTT_3 = functionals.make_translation(pS_3, 1, 1, 1)
    pTT_4 = functionals.make_translation(pS_4, 1, 1, 1)
    pTT_5 = functionals.make_translation(pS_5, 1, 1, 1)
    pTT_6 = functionals.make_translation(pS_6, 1, 1, 1)
    pTT_7 = functionals.make_translation(pS_7, 1, 1, 1)
    pTT_8 = functionals.make_translation(pS_8, 1, 1, 1)
    cube2 = functionals.Box.from_points(pTT_1, pTT_2, pTT_3, pTT_4, pTT_5, pTT_6, pTT_7, pTT_8)
    M_1 = functionals.get_translate_matrix(1, 1, 1) @ functionals.get_scale_matrix(2, 2, 2) @ functionals.get_translate_matrix(-1, -1, -1)
    print("Перша трансформація:")
    cube2.printer()
    print(M_1)
    M_2 = M_1 @ functionals.get_R_z_matrix(math.radians(90))
    pR_1 = M_2 @ cube1.p1
    pR_2 = M_2 @ cube1.p2
    pR_3 = M_2 @ cube1.p3
    pR_4 = M_2 @ cube1.p4
    pR_5 = M_2 @ cube1.p5
    pR_6 = M_2 @ cube1.p6
    pR_7 = M_2 @ cube1.p7
    pR_8 = M_2 @ cube1.p8
    cube3 = functionals.Box.from_points(pR_1, pR_2, pR_3, pR_4, pR_5, pR_6, pR_7, pR_8)
    print("Друга трансформація:")
    cube3.printer()
    print(M_2)
    M_3 = functionals.get_translate_matrix(-3, 4, 2)
    M = M_3 @ M_2
    pT3_1 = M @ cube1.p1
    pT3_2 = M @ cube1.p2
    pT3_3 = M @ cube1.p3
    pT3_4 = M @ cube1.p4
    pT3_5 = M @ cube1.p5
    pT3_6 = M @ cube1.p6
    pT3_7 = M @ cube1.p7
    pT3_8 = M @ cube1.p8
    cube4 = functionals.Box.from_points(pT3_1, pT3_2, pT3_3, pT3_4, pT3_5, pT3_6, pT3_7, pT3_8)
    print("Третя трансформація:")
    cube4.printer()
    print(M_3)
    print("Повна матриця трансформації:")
    print(M)
    return M